apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: shop-products-switch-prod-
  namespace: user1-continuous-deployment
spec:
  pipelineRef:
    name: pipeline-blue-green-environments
  params:
  - name: APP
    value: products
  - name: STEP
    value: "switch"
  - name: NEW_IMAGE_TAG
    value: "v1.1.1"
  - name: NAMESPACE
    value: "user1-prod"
  - name: REPO_FULL_NAME
    value: jerosa/cloud-native-deployment-strategies
  - name: ENV
    value: prod
  workspaces:
  - name: app-source
    persistentVolumeClaim:
      claimName: workspace-pvc-shop-cd-new-version